name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Releasing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Creating .npmrc file
        run: |
          cp .npmrc.template .npmrc
          sed -i "s/INSERT_ACCESS_TOKEN_HERE/$NPM_TOKEN/g" .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun i --frozen-lockfile

      - name: Create Release Pull Request or Publish to Github Registry
        uses: changesets/action@v1
        with:
          publish: bunx changeset publish
          version: bunx changeset version
          commit: "chore: release package(s)"
          title: "chore: release package(s)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
